txt = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(txt))
print('Só tem espaço? ', txt.isspace())
print('É um número? ', txt.isnumeric())
print('É alfabetico? ', txt.isalpha())
print('É alfanúmerico? ', txt.isalnum())
print('Esta maiusculo?', txt.isupper())
print('Esta minusculo?', txt.islower())
print('Esta capitalizado? ', txt.istitle())